name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kciter/aws-ecr-action@v3
        with:
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          repo: ${{ github.event.repository.name }}
          tags: latest
          create_repo: true

  build-push-docker-eu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kciter/aws-ecr-action@v3
        with:
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-central-1
          repo: ${{ github.event.repository.name }}
          tags: latest
          create_repo: true

  deploy:
    needs:
      - build-push-docker
    uses: integration-app/workflows/.github/workflows/deploy_app_to_prod.yml@main
    with:
      application: ${{ github.event.repository.name }}
    secrets: inherit
