name: Pull Request Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: 'End-to-end Test'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: npm
      - name: Install NPM
        run: npm install
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_USE_NGROK: 1
          envkey_BASE_URI: 'http://endpoint:3000'
          envkey_SECRET: 'asdfsadfasdflsadf28tu-9fasfasfhs3!##s'
          envkey_S3_BUCKET: iapp-connectors-dev
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_AWS_REGION: ${{ secrets.AWS_REGION }}
          envkey_TEST_ACCESS_TOKEN: ${{ secrets.TEST_ACCESS_TOKEN }}
      - name: Run Tests
        run: docker-compose run test
      - name: Show Docker Logs
        run: docker-compose logs
        if: failure()
